### ISSUE TITLE
fine tuning时报错，是训练集的图片尺寸问题吗？

### ISSUE THREAD

**Issue by hai4john** [JiangWeibeta/MLIC#7]
fine tuning时，报如下错误，是对训练集的图片尺寸有要求吗？
24-04-10 10:36:36.398 - INFO: Learning rate: 0.0001
Traceback (most recent call last):
File "/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/playground/train.py", line 162, in
main()
File "/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/playground/train.py", line 124, in main
current_step = train_one_epoch(
File "/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/utils/training.py", line 24, in train_one_epoch
optimizer.step()
File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
return wrapped(*args, **kwargs)
File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 385, in wrapper
out = func(*args, **kwargs)
File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
ret = func(self, *args, **kwargs)
File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 166, in step
adam(
File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 316, in adam
func(params,
File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 520, in _multi_tensor_adam
torch.foreach_lerp(device_exp_avgs, device_grads, 1 - beta1)
RuntimeError: The size of tensor a (32) must match the size of tensor b (192) at non-singleton dimension 0

有看到 dataload部分
train_transforms = transforms.Compose(
[transforms.RandomCrop(args.patch_size), transforms.ToTensor()]
)
对图像进行裁剪，理论上只要数据集中图片尺寸大于 args.patch_size 就行，对吧？

**Comment by YY-RR-ZZ** [comment]
> 微调时，报如下错误，是对训练集的图片尺寸有要求吗？ 24-04-10 10:36:36.398 - INFO: 学习率: 0.0001 Traceback (最近一次调用最后): File "/home/zhanghh /work/JiangWeibeta/MLIC/MLIC++/playground/train.py”，第 162 行，在 main() 文件“/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/playground/train.py”，第 124 行，在 main 中 current_step = train_one_epoch( File "/home/zhanghh/work/JiangWeibeta/MLIC/MLIC++/utils/training.py", 第 24 行，在 train_one_epoch optimizationr.step() 文件中“/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py”, 第 75 行, 在包装器中 返回已包装(*args, **kwargs) 文件“ /home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", 第 385 行，在包装器 out = func(*args, **kwargs) 文件“ /home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", 第 76 行，在 _use_grad ret = func(self, *args, **kwargs) 文件“/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py”, 第 166 行, 在步骤 adam( 文件“/home/zhanghh/work/JiangWeibeta /MLIC/venv/lib/python3.10/site-packages/torch/optim/adam.py", 第 316 行, 在 adam func(params, File "/home/zhanghh/work/JiangWeibeta/MLIC/venv/lib/ python3.10/site-packages/torch/optim/adam.py", 第 520 行，位于 _multi_tensor_adam torch.foreach_lerp(device_exp_avgs, device_grads, 1 - beta1) RuntimeError: 张量 a (32) 的大小必须与张量的大小匹配b (192) 在非单例维度 0
> 
> 有看到dataload部分 train_transforms = transforms.Compose( [transforms.RandomCrop(args.patch_size),transforms.ToTensor()] ) 对图像进行正规的，理论上只要数据集中图片尺寸大于args.patch_size就行，对吧？

您好，我也遇到了这个问题，请问您解决了吗?

**Comment by JiangWeibeta** [comment]
需要patch size的宽和高是64的倍数

**Comment by YY-RR-ZZ** [comment]
> 需要patch size的宽和高是64的倍数
您好，感谢您的答复，我在训练阶段没有改动patch_size，它还是256×256，只是我加载了您提供的预训练权重，如果不加载预训练权重的话(去掉-c)，可以正常训练，但是加上-c /home/MLIC/snap/mlicpp_new_mse_q6.pth.tar它报错tensor维度不匹配。
work_path=$(dirname $0)
export PYTHONPATH=..:$PYTHONPATH
nohup python train.py --metrics mse --exp mlicpp_mse_q6 -c /home/MLIC/snap/mlicpp_new_mse_q6.pth.tar --gpu_id 1 --lambda 0.0483 -lr 1e-4 --clip_max_norm 1.0 --seed 1984 --batch-size 32 & > 0035v2.txt

报错如下
24-10-23 15:15:48.172 - INFO: Learning rate: 0.0001
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    main()
  File "train.py", line 181, in main
    current_step = train_one_epoch(
  File "/home/zyr/MLIC/MLIC++/utils/training.py", line 24, in train_one_epoch
    optimizer.step()
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/adam.py", line 166, in step
    adam(
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/adam.py", line 316, in adam
    func(params,
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/adam.py", line 520, in _multi_tensor_adam
    torch._foreach_lerp_(device_exp_avgs, device_grads, 1 - beta1)
RuntimeError: The size of tensor a (32) must match the size of tensor b (192) at non-singleton dimension 0

**Comment by YY-RR-ZZ** [comment]
> 需要patch size的宽和高是64的倍数

您好，感谢您的答复，我在训练阶段patch_size还是256×256，没有改动，只是添加了您的预训练权重fine tuning的时候报错了tensor维度不匹配。如果不加载预训练权重的时候，是可以正常训练的

work_path=$(dirname $0)
export PYTHONPATH=..:$PYTHONPATH
nohup python train.py --metrics mse --exp mlicpp_mse_q6 -c /home/zyr/MLIC/snap/mlicpp_new_mse_q6.pth.tar --gpu_id 1 --lambda 0.0483 -lr 1e-4 --clip_max_norm 1.0 --seed 1984 --batch-size 32 & > 0035v2.txt

24-10-23 15:15:48.172 - INFO: Learning rate: 0.0001
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    main()
  File "train.py", line 181, in main
    current_step = train_one_epoch(
  File "/home/zyr/MLIC/MLIC++/utils/training.py", line 24, in train_one_epoch
    optimizer.step()
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/adam.py", line 166, in step
    adam(
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/adam.py", line 316, in adam
    func(params,
  File "/home/zyr/anaconda3/envs/mlic/lib/python3.8/site-packages/torch/optim/adam.py", line 520, in _multi_tensor_adam
    torch._foreach_lerp_(device_exp_avgs, device_grads, 1 - beta1)
RuntimeError: The size of tensor a (32) must match the size of tensor b (192) at non-singleton dimension 0

**Comment by JiangWeibeta** [comment]
To use old weights, you should use LatentResidualPredictionOld and SynthesisTransformOld. 可以检查一下是否使用的是这两个模块。
